import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Featured from '../components/Featured';
import List from '../components/List';
import axios from 'axios';
import { useState } from "react";
import Add from "../components/Add";
import AddButton from "../components/AddButton";


export default function Home({list , admin}) {
  const [close, setClose] = useState(true);
  return (
    <div className={styles.container}>
    
      <Head>
        <title>Rakesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured/>
      {<AddButton setClose={setClose} />}
    
      <List list={list} />
      {!close && <Add setClose={setClose} />}
     
    
    </div>
  )
}

export const getServerSideProps= async (ctx) =>{

  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  const res = await axios.get("http://localhost:3000/api/products");
  return{
    props: {
      list: res.data,
      admin,
    }
  }

}